{% set name = "mlflow" %}
{% set version = "1.16.0" %}
{% if mlflow_variant == "skinny" %}
{% set mlflow_suffix = "-skinny" %}
{% set mlflow_other = "" %}
{% else %}
{% set mlflow_suffix = "" %}
{% set mlflow_other = "-skinny" %}
{% endif %}

package:
  name: {{ name|lower }}{{ mlflow_suffix }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dba1c85e1f81616941b18087e5309490760e388fcc5b66479d909a2782082767

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - alembic <=1.4.1  # [mlflow_variant != "skinny"]
    - click >=7.0
    - cloudpickle
    - databricks-cli >=0.8.7
    - docker-py >=4.0.0  # [mlflow_variant != "skinny"]
    - entrypoints
    - flask  # [mlflow_variant != "skinny"]
    - gitpython >=2.1.0
    - gunicorn  # [not win and mlflow_variant != "skinny"]
    - numpy  # [mlflow_variant != "skinny"]
    - pandas  # [mlflow_variant != "skinny"]
    - prometheus_flask_exporter  # [mlflow_variant != "skinny"]
    - protobuf >=3.6.0
    - python
    - pytz
    - pyyaml
    - querystring_parser  # [mlflow_variant != "skinny"]
    - requests >=2.17.3
    - sqlalchemy  # [mlflow_variant != "skinny"]
    - sqlparse >=0.3.1  # [mlflow_variant != "skinny"]
    - waitress  # [win and mlflow_variant != "skinny"]
  run_constrained:
    - mlflow{{ mlflow_other }} <0a0

test:
  imports:
    - mlflow
    - mlflow.azureml  # [mlflow_variant != "skinny"]
    - mlflow.entities
    - mlflow.models  # [mlflow_variant != "skinny"]
    - mlflow.projects
    - mlflow.protos
    - mlflow.pyfunc  # [mlflow_variant != "skinny"]
    - mlflow.pytorch  # [mlflow_variant != "skinny"]
    - mlflow.rfunc
    - mlflow.sagemaker  # [mlflow_variant != "skinny"]
    - mlflow.server  # [mlflow_variant != "skinny"]
    - mlflow.server.prometheus_exporter  # [mlflow_variant != "skinny"]
    - mlflow.store
    - mlflow.tracking
    - mlflow.utils
  commands:
    - mlflow --help  # [not win]
    - pip check  # [not win]
  requires:
    - pip

outputs:
  - name: mlflow{{ mlflow_suffix }}
    version: {{ version }}
    files:
      - bin/mlflow*    # [unix]
      - lib/python{{ PY_VER }}/site-packages/mlflow    # [unix]
      - lib/python{{ PY_VER }}/site-packages/mlflow-*    # [unix]
      - Scripts\mlflow*     # [win]
      - Lib\site-packages\mlflow      # [win]
      - Lib\site-packages\mlflow-*      # [win]
  - name: mlflow-ui-dbg{{ mlflow_suffix }}
    build:
      skip: true  # [mlflow_variant == "skinny"]
    version: {{ version }}
    requirements:
      # we need to use python in host to generate a unique build string
      # otherwise the exact pin below means this package gets made only
      # for one python version
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('mlflow' + mlflow_suffix, exact=True) }}
    script: install_maps.bat  # [win]
    script: install_maps.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  feedstock-name: mlflow
  recipe-maintainers:
    - aarondav
    - ahirreddy
    - andrewmchen
    - aveshcsingh
    - dbczumar
    - jaroslawk
    - mateiz
    - mparkhe
    - pogil
    - smurching
    - sueann
    - tomasatdatabricks
    - xhochy
    - zangr
