{% set name = "mlflow" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9116d82be380c32fa465049d14b217c4c200ad11614f4c6674e6b524b2935206

build:
  number: 0
  skip: True  # [py<35]
  # Not possible anymore because of the waitress/gunicorn split
  # noarch: python
  # entry_points:
  #   - mlflow=mlflow.cli:cli

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - alembic
    - click >=7.0
    - cloudpickle
    - databricks-cli >=0.8.7
    - docker-py >=4
    - entrypoints
    - flask
    - gitpython >=2.1.0
    - gorilla
    - gunicorn  # [not win]
    - waitress  # [win]
    - numpy
    - pandas
    - pip
    - protobuf >=3.6.0
    - python-dateutil
    - pyyaml
    - querystring_parser
    - requests >=2.17.3
    - simplejson
    - six >=1.10.0
    - sqlalchemy
    - sqlparse

test:
  imports:
    - mlflow
    - mlflow.azureml
    - mlflow.entities
    - mlflow.models
    - mlflow.projects
    - mlflow.protos
    - mlflow.pyfunc
    - mlflow.pytorch
    - mlflow.rfunc
    - mlflow.sagemaker
    - mlflow.server
    - mlflow.store
    - mlflow.tracking
    - mlflow.utils
  commands:
    - mlflow --help  # [not win]

outputs:
  - name: mlflow
    version: {{ version }}
    files:
      - "bin/mlflow*"  # [unix]
      - "lib/python{{ PY_VER }}/site-packages/mlflow"  # [unix]
      - "lib/python{{ PY_VER }}/site-packages/mlflow-*"  # [unix]
      - "Scripts\\mlflow*"  # [win]
      - "Lib\\site-packages\\mlflow"  # [win]
      - "Lib\\site-packages\\mlflow-*"  # [win]
  - name: mlflow-ui-dbg
    version: {{ version }}
    requirements:
      run:
        - python
        - {{ pin_subpackage('mlflow', exact=True) }}
    script: install_maps.bat  # [win]
    script: install_maps.sh  # [unix]


about:
  home: https://mlflow.org/
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLflow is an open source platform for the machine learning lifecycle.
  doc_url: https://mlflow.org
  dev_url: https://github.com/mlflow/mlflow

extra:
  recipe-maintainers:
    - andrewmchen
    - jaroslawk
    - ahirreddy
    - aarondav
    - mateiz
    - dbczumar
    - smurching
    - tomasatdatabricks
    - sueann
    - pogil
    - mparkhe
    - zangr
    - xhochy
