travis:
  secure:
    BINSTAR_TOKEN: FGBoKkVEKCZBrP1+nJx/fuJKrYa+fP8dg/DT7zDzH3RkeMoGOc1SmPGvoXuJRD3VKh9zNp1DFwWSghpgpW5Lcq3Y5Bv+0RNanc5X7ncaJHx1YMjH3dktSR1Qsb5KB6wBaZ0id3y3Y8oXl+24AESTd13ANX8xExPIkLx0s4JDyh4lGEaiHwBJOfbn8cFogiBj/sxThcoPM9W4AggbHrXywDliIJ2scR51WUQ0XhEpMPJO+Us+85CdJH2KIK/hFx6JwjMDglL22KrrYgTn2k+i0y1rJ0R3/+zljg8wJXF08kqtsKh+Ky7e93ieOz7EhYFtYgx3FBWjjxSfnf8RYVZpke/Xyi2r6R4fJfrXuGmPXzN/X4NPjyZAVb2dwPggerN/+bVtozOYqccbm31SMHCHA40KpT0IL4oHV/VH1JinT1JN4rUznHY8tPJHd6os1jN/tK28p1xhY86Ye+8cM2q+cr0tb4nmtRvalR+fwlAkLMJ8+gw/AHRzjv+h92S5oK7IRbosVlo+R+jiSAF154hWABSWoWzs5O3iOAV31XUoKZhm/wY832tVdnnDArJwZHmfq/WAcKZ5956s9bqVZ7JrGy+ufSHxOIZ1JjUy4Bj50lLbS163PYyh0LPaGqIRK/CwsFioEMwClpGhZe+1SljAvStflyf0p0LunL0tHPiYusQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
